-- DROP TABLE IF EXISTS schema_migrations CASCADE;
DROP TABLE IF EXISTS product CASCADE;
DROP TABLE IF EXISTS shelf CASCADE;
DROP TABLE IF EXISTS productShelf CASCADE;
DROP TABLE IF EXISTS orders CASCADE;
DROP TABLE IF EXISTS orderDetail CASCADE;