INSERT INTO product (product_name, category, price) VALUES('Ноутбук', 'Электроника', 400);
INSERT INTO product (product_name, category, price) VALUES('Телевизор', 'Электроника', 250);
INSERT INTO product (product_name, category, price) VALUES('Телефон', 'Электроника', 300);
INSERT INTO product (product_name, category, price) VALUES('Системный блок', 'Электроника', 1000);
INSERT INTO product (product_name, category, price) VALUES('Часы', 'Электроника', 60);
INSERT INTO product (product_name, category, price) VALUES('Микрофон', 'Электроника', 20);

INSERT INTO product (product_name, category, price) VALUES ('Наушники', 'Электроника', 80);
INSERT INTO product (product_name, category, price) VALUES ('Портативная зарядка', 'Электроника', 50);
INSERT INTO product (product_name, category, price) VALUES ('Фитнес-трекер', 'Электроника', 120);
INSERT INTO product (product_name, category, price) VALUES ('USB флешка', 'Электроника', 25);
INSERT INTO product (product_name, category, price) VALUES ('Клавиатура', 'Электроника', 70);
INSERT INTO product (product_name, category, price) VALUES ('Мышь', 'Электроника', 40);
INSERT INTO product (product_name, category, price) VALUES ('Wi-Fi маршрутизатор', 'Электроника', 90);
INSERT INTO product (product_name, category, price) VALUES ('Жесткий диск SSD', 'Электроника', 150);
INSERT INTO product (product_name, category, price) VALUES ('Компьютерная мышь', 'Электроника', 30);
INSERT INTO product (product_name, category, price) VALUES ('Bluetooth колонка', 'Электроника', 70);
INSERT INTO product (product_name, category, price) VALUES ('Принтер', 'Электроника', 200);
INSERT INTO product (product_name, category, price) VALUES ('HDMI кабель', 'Электроника', 15);
INSERT INTO product (product_name, category, price) VALUES ('Web-камера', 'Электроника', 50);
INSERT INTO product (product_name, category, price) VALUES ('Гарнитура', 'Электроника', 90);
INSERT INTO product (product_name, category, price) VALUES ('Мышка для гейминга', 'Электроника', 100);
INSERT INTO product (product_name, category, price) VALUES ('Термометр для кухни', 'Электроника', 20);
INSERT INTO product (product_name, category, price) VALUES ('Карта памяти SD', 'Электроника', 35);
INSERT INTO product (product_name, category, price) VALUES ('Наушники с микрофоном', 'Электроника', 60);
INSERT INTO product (product_name, category, price) VALUES ('Игровая консоль', 'Электроника', 300);
INSERT INTO product (product_name, category, price) VALUES ('Компьютерный монитор', 'Электроника', 180);

INSERT INTO product (product_name, category, price) VALUES ('Футбольный мяч', 'Спорт', 20);
INSERT INTO product (product_name, category, price) VALUES ('Баскетбольный мяч', 'Спорт', 25);
INSERT INTO product (product_name, category, price) VALUES ('Беговая дорожка', 'Спорт', 500);
INSERT INTO product (product_name, category, price) VALUES ('Велосипед', 'Спорт', 300);
INSERT INTO product (product_name, category, price) VALUES ('Теннисная ракетка', 'Спорт', 60);
INSERT INTO product (product_name, category, price) VALUES ('Гантели', 'Спорт', 50);
INSERT INTO product (product_name, category, price) VALUES ('Мяч для настольного тенниса', 'Спорт', 15);
INSERT INTO product (product_name, category, price) VALUES ('Йога-коврик', 'Спорт', 20);
INSERT INTO product (product_name, category, price) VALUES ('Роликовые коньки', 'Спорт', 70);
INSERT INTO product (product_name, category, price) VALUES ('Боксерские перчатки', 'Спорт', 40);
INSERT INTO product (product_name, category, price) VALUES ('Массажный мяч', 'Спорт', 10);
INSERT INTO product (product_name, category, price) VALUES ('Ласты для плавания', 'Спорт', 30);
INSERT INTO product (product_name, category, price) VALUES ('Тренажер для пресса', 'Спорт', 80);
INSERT INTO product (product_name, category, price) VALUES ('Футбольные ворота', 'Спорт', 100);
INSERT INTO product (product_name, category, price) VALUES ('Беговел', 'Спорт', 50);
INSERT INTO product (product_name, category, price) VALUES ('Спортивные очки', 'Спорт', 40);
INSERT INTO product (product_name, category, price) VALUES ('Теннисный стол', 'Спорт', 150);
INSERT INTO product (product_name, category, price) VALUES ('Велотренажер', 'Спорт', 200);
INSERT INTO product (product_name, category, price) VALUES ('Футбольные бутсы', 'Спорт', 60);
INSERT INTO product (product_name, category, price) VALUES ('Скакалка', 'Спорт', 15);

INSERT INTO product (product_name, category, price) VALUES ('Книга "Война и мир"', 'Книги', 15);
INSERT INTO product (product_name, category, price) VALUES ('Книга "Преступление и наказание"', 'Книги', 10);
INSERT INTO product (product_name, category, price) VALUES ('Книга "Гарри Поттер и философский камень"', 'Книги', 12);
INSERT INTO product (product_name, category, price) VALUES ('Книга "Гарри Поттер и узник Азкабана"', 'Книги', 14);
INSERT INTO product (product_name, category, price) VALUES ('Книга "1984"', 'Книги', 11);
INSERT INTO product (product_name, category, price) VALUES ('Книга "Мастер и Маргарита"', 'Книги', 13);
INSERT INTO product (product_name, category, price) VALUES ('Книга "Пикник на обочине"', 'Книги', 9);
INSERT INTO product (product_name, category, price) VALUES ('Книга "Властелин колец"', 'Книги', 18);
INSERT INTO product (product_name, category, price) VALUES ('Книга "Алхимик"', 'Книги', 8);
INSERT INTO product (product_name, category, price) VALUES ('Книга "Тихий Дон"', 'Книги', 17);
INSERT INTO product (product_name, category, price) VALUES ('Книга "Маленький принц"', 'Книги', 7);
INSERT INTO product (product_name, category, price) VALUES ('Книга "Мастер и Маргарита"', 'Книги', 13);
INSERT INTO product (product_name, category, price) VALUES ('Книга "Три товарища"', 'Книги', 16);
INSERT INTO product (product_name, category, price) VALUES ('Книга "Идиот"', 'Книги', 11);
INSERT INTO product (product_name, category, price) VALUES ('Книга "Метро 2033"', 'Книги', 10);
INSERT INTO product (product_name, category, price) VALUES ('Книга "Мастер и Маргарита"', 'Книги', 13);
INSERT INTO product (product_name, category, price) VALUES ('Книга "Анна Каренина"', 'Книги', 15);
INSERT INTO product (product_name, category, price) VALUES ('Книга "Герой нашего времени"', 'Книги', 9);
INSERT INTO product (product_name, category, price) VALUES ('Книга "Подросток"', 'Книги', 8);
INSERT INTO product (product_name, category, price) VALUES ('Книга "Записки из подполья"', 'Книги', 12);

INSERT INTO product (product_name, category, price) VALUES ('Стиральная машина', 'Бытовая техника', 400);
INSERT INTO product (product_name, category, price) VALUES ('Холодильник', 'Бытовая техника', 600);
INSERT INTO product (product_name, category, price) VALUES ('Пылесос', 'Бытовая техника', 150);
INSERT INTO product (product_name, category, price) VALUES ('Электрический чайник', 'Бытовая техника', 30);
INSERT INTO product (product_name, category, price) VALUES ('Микроволновая печь', 'Бытовая техника', 100);
INSERT INTO product (product_name, category, price) VALUES ('Утюг', 'Бытовая техника', 20);
INSERT INTO product (product_name, category, price) VALUES ('Тостер', 'Бытовая техника', 25);
INSERT INTO product (product_name, category, price) VALUES ('Кофеварка', 'Бытовая техника', 50);
INSERT INTO product (product_name, category, price) VALUES ('Блендер', 'Бытовая техника', 40);
INSERT INTO product (product_name, category, price) VALUES ('Фен для волос', 'Бытовая техника', 15);
INSERT INTO product (product_name, category, price) VALUES ('Утюжок для волос', 'Бытовая техника', 25);
INSERT INTO product (product_name, category, price) VALUES ('Электробритва', 'Бытовая техника', 35);
INSERT INTO product (product_name, category, price) VALUES ('Электрическая зубная щетка', 'Бытовая техника', 20);
INSERT INTO product (product_name, category, price) VALUES ('Весы кухонные', 'Бытовая техника', 30);
INSERT INTO product (product_name, category, price) VALUES ('Мясорубка', 'Бытовая техника', 50);
INSERT INTO product (product_name, category, price) VALUES ('Соковыжималка', 'Бытовая техника', 40);
INSERT INTO product (product_name, category, price) VALUES ('Кухонный комбайн', 'Бытовая техника', 100);
INSERT INTO product (product_name, category, price) VALUES ('Мясорезка', 'Бытовая техника', 70);
INSERT INTO product (product_name, category, price) VALUES ('Электрочайник', 'Бытовая техника', 25);
INSERT INTO product (product_name, category, price) VALUES ('Фритюрница', 'Бытовая техника', 50);

INSERT INTO product (product_name, category, price) VALUES ('Молоко', 'Еда', 2);
INSERT INTO product (product_name, category, price) VALUES ('Хлеб', 'Еда', 1);
INSERT INTO product (product_name, category, price) VALUES ('Яйца', 'Еда', 3);
INSERT INTO product (product_name, category, price) VALUES ('Масло сливочное', 'Еда', 2);
INSERT INTO product (product_name, category, price) VALUES ('Сахар', 'Еда', 1);
INSERT INTO product (product_name, category, price) VALUES ('Мука', 'Еда', 1);
INSERT INTO product (product_name, category, price) VALUES ('Рис', 'Еда', 2);
INSERT INTO product (product_name, category, price) VALUES ('Макароны', 'Еда', 1);
INSERT INTO product (product_name, category, price) VALUES ('Картофель', 'Еда', 0);
INSERT INTO product (product_name, category, price) VALUES ('Морковь', 'Еда', 1);
INSERT INTO product (product_name, category, price) VALUES ('Огурцы', 'Еда', 1);
INSERT INTO product (product_name, category, price) VALUES ('Помидоры', 'Еда', 1);
INSERT INTO product (product_name, category, price) VALUES ('Курица', 'Еда', 4);
INSERT INTO product (product_name, category, price) VALUES ('Говядина', 'Еда', 6);
INSERT INTO product (product_name, category, price) VALUES ('Свинина', 'Еда', 5);
INSERT INTO product (product_name, category, price) VALUES ('Рыба', 'Еда', 7);
INSERT INTO product (product_name, category, price) VALUES ('Сыр', 'Еда', 3);
INSERT INTO product (product_name, category, price) VALUES ('Колбаса', 'Еда', 4);
INSERT INTO product (product_name, category, price) VALUES ('Сок', 'Еда', 2);
INSERT INTO product (product_name, category, price) VALUES ('Чай', 'Еда', 1);


